In [ ]:
from google.colab import drive
import pandas as pd
import glob
import os

# Mount your Google Drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
directory = '/content/drive/MyDrive/water paper/IrelandPivoted/'
print(os.listdir(directory))
csv_files = glob.glob(directory + '/*.csv')
print(csv_files)
dfs = []
encoding = 'ISO-8859-1'
# Loop over each CSV file and read it into a DataFrame
for filename in csv_files:
    print("Processed File: ", filename)
    df = pd.read_csv(filename, encoding=encoding)
    selected_columns = [
    'WaterbodyName',
    'Waterbodytype',
    'SampleDate',
    'Alkalinity-total (as CaCO3)',
    'Ammonia-Total (as N)',
    'BOD - 5 days (Total)',
    'Chloride',
    'Conductivity @25Â°C',
    'Dissolved Oxygen',
    'ortho-Phosphate (as P) - unspecified',
    'pH',
    'Temperature',
    'Total Hardness (as CaCO3)',
    'Total Oxidised Nitrogen (as N)',
    'Nitrate (as N)']
    df = df.rename(columns={'Conductivity @25?øC': 'Conductivity @25Â°C'})
    df = df.rename(columns={'Conductivity @25??C': 'Conductivity @25Â°C'})

    new_df = df[selected_columns]
    new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
    new_df['Waterbodytype'].fillna(method='ffill', inplace=True)

    # Extract the filename from the path
    filenamep = filename.split('/')[-1].split('.')[0]

    # Add the filename to the "WaterbodyName" column
    new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
    dfs.append(new_df)

    new_df.to_csv(directory+'f_'+filenamep+'.csv', index=False)

['Ballyteigue-Bannow.csv', 'Bandonllen.csv', 'Barrow.csv', 'Blacksod-Broadhaven.csv', 'Suir.csv', 'Boyne.csv', 'Nore.csv', 'Erne.csv', 'Slaney _ Wexford Harbour.csv', 'Liffey and Dublin Bay.csv', 'Moy _ Killala Bay.csv', 'Corrib.csv', 'Ovoca-Vartry.csv', 'Shannon Estuary South.csv', 'Laune-Maine-Dingle Bay.csv', 'Lower Shannon (C).csv', 'Lower Shannon (A).csv', 'Sligo Bay _ Drowse.csv', 'Lower Shannon (D).csv', 'Tralee Bay-Feale.csv', 'Shannon Estuary North.csv', 'Erriff-Clew Bay.csv', 'Gweebarra-Sheephaven.csv', 'Upper Shannon (F).csv', 'Upper Shannon (C).csv', 'Lower Shannon (B).csv', 'Lough Swilly.csv', 'Galway Bay South East.csv', 'Foyle.csv', 'Dunmanus-Bantry-Kenmare.csv', 'Upper Shannon (A).csv', 'Nanny-Delvin.csv', 'Upper Shannon (D).csv', 'Colligan-Mahon.csv', 'Owenavorragh.csv', 'foyal.csv', 'Galway Bay North.csv', 'Mal Bay.csv', 'Lough Neagh _ Lower Bann.csv', 'Donegal Bay North.csv', 'Upper Shannon (B).csv', 'Donagh-Moville.csv', 'Upper Shannon (E).csv', 'Blackwater_Munster.csv', 'Newry, Fane, Glyde and Dee.csv', 'Lee, Cork Harbour and Youghal Bay.csv', 'Cork Harbour, Moy Killala.csv']
['/content/drive/MyDrive/water paper/IrelandPivoted/Ballyteigue-Bannow.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Bandonllen.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Barrow.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Blacksod-Broadhaven.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Suir.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Boyne.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Nore.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Erne.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Slaney _ Wexford Harbour.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Liffey and Dublin Bay.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Moy _ Killala Bay.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Corrib.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Ovoca-Vartry.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Shannon Estuary South.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Laune-Maine-Dingle Bay.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Lower Shannon (C).csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Lower Shannon (A).csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Sligo Bay _ Drowse.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Lower Shannon (D).csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Tralee Bay-Feale.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Shannon Estuary North.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Erriff-Clew Bay.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Gweebarra-Sheephaven.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Upper Shannon (F).csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Upper Shannon (C).csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Lower Shannon (B).csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Lough Swilly.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Galway Bay South East.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Foyle.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Dunmanus-Bantry-Kenmare.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Upper Shannon (A).csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Nanny-Delvin.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Upper Shannon (D).csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Colligan-Mahon.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Owenavorragh.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/foyal.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Galway Bay North.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Mal Bay.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Lough Neagh _ Lower Bann.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Donegal Bay North.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Upper Shannon (B).csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Donagh-Moville.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Upper Shannon (E).csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Blackwater_Munster.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Newry, Fane, Glyde and Dee.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Lee, Cork Harbour and Youghal Bay.csv', '/content/drive/MyDrive/water paper/IrelandPivoted/Cork Harbour, Moy Killala.csv']
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Ballyteigue-Bannow.csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Bandonllen.csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Barrow.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Blacksod-Broadhaven.csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Suir.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Boyne.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Nore.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Erne.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Slaney _ Wexford Harbour.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Liffey and Dublin Bay.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Moy _ Killala Bay.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Corrib.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Ovoca-Vartry.csv

<ipython-input-10-efb24eb1a6ce>:10: DtypeWarning: Columns (0,1) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(filename, encoding=encoding)
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Shannon Estuary South.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Laune-Maine-Dingle Bay.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Lower Shannon (C).csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Lower Shannon (A).csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Sligo Bay _ Drowse.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Lower Shannon (D).csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Tralee Bay-Feale.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Shannon Estuary North.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Erriff-Clew Bay.csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Gweebarra-Sheephaven.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Upper Shannon (F).csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Upper Shannon (C).csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Lower Shannon (B).csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Lough Swilly.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Galway Bay South East.csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Foyle.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Dunmanus-Bantry-Kenmare.csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Upper Shannon (A).csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Nanny-Delvin.csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Upper Shannon (D).csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Colligan-Mahon.csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Owenavorragh.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/foyal.csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Galway Bay North.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Mal Bay.csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Lough Neagh _ Lower Bann.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Donegal Bay North.csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Upper Shannon (B).csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Donagh-Moville.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Upper Shannon (E).csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Blackwater_Munster.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Newry, Fane, Glyde and Dee.csv
Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Lee, Cork Harbour and Youghal Bay.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']
<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Processed File:  /content/drive/MyDrive/water paper/IrelandPivoted/Cork Harbour, Moy Killala.csv

<ipython-input-10-efb24eb1a6ce>:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Waterbodytype'].fillna(method='ffill', inplace=True)
<ipython-input-10-efb24eb1a6ce>:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['WaterbodyName'] = filenamep + ', ' + new_df['WaterbodyName']

Combine All pivoted files having selected columns from a Drive Folder

---

In [ ]:
from google.colab import drive
import pandas as pd
import glob
import os

drive.mount('/content/drive')
directory = '/content/drive/MyDrive/water paper/new added columns last'

print(os.listdir(directory))
csv_files = glob.glob(directory + '/*.csv')
print(csv_files)

dfs = []

for filename in csv_files:
    df = pd.read_csv(filename)
    dfs.append(df)
print(dfs)
merged_df = pd.concat(dfs, ignore_index=True)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
['f_Ballyteigue-Bannow.csv', 'f_Bandonllen.csv', 'f_Barrow.csv', 'f_Blacksod-Broadhaven.csv', 'f_Suir.csv', 'f_Boyne.csv', 'f_Nore.csv', 'f_Erne.csv', 'f_Slaney _ Wexford Harbour.csv', 'f_Liffey and Dublin Bay.csv', 'f_Moy _ Killala Bay.csv', 'f_Corrib.csv', 'f_Ovoca-Vartry.csv', 'f_Shannon Estuary South.csv', 'f_Laune-Maine-Dingle Bay.csv', 'f_Lower Shannon (C).csv', 'f_Lower Shannon (A).csv', 'f_Sligo Bay _ Drowse.csv', 'f_Lower Shannon (D).csv', 'f_Tralee Bay-Feale.csv', 'f_Shannon Estuary North.csv', 'f_Erriff-Clew Bay.csv', 'f_Gweebarra-Sheephaven.csv', 'f_Upper Shannon (F).csv', 'f_Upper Shannon (C).csv', 'f_Lower Shannon (B).csv', 'f_Lough Swilly.csv', 'f_Galway Bay South East.csv', 'f_Foyle.csv', 'f_Dunmanus-Bantry-Kenmare.csv', 'f_Upper Shannon (A).csv', 'f_Nanny-Delvin.csv', 'f_Upper Shannon (D).csv', 'f_Colligan-Mahon.csv', 'f_Owenavorragh.csv', 'f_foyal.csv', 'f_Galway Bay North.csv', 'f_Mal Bay.csv', 'f_Lough Neagh _ Lower Bann.csv', 'f_Donegal Bay North.csv', 'f_Upper Shannon (B).csv', 'f_Donagh-Moville.csv', 'f_Upper Shannon (E).csv', 'f_Blackwater_Munster.csv', 'f_Newry, Fane, Glyde and Dee.csv', 'f_Lee, Cork Harbour and Youghal Bay.csv', 'f_Cork Harbour, Moy Killala.csv']
['/content/drive/MyDrive/water paper/new added columns last/f_Ballyteigue-Bannow.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Bandonllen.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Barrow.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Blacksod-Broadhaven.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Suir.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Boyne.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Nore.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Erne.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Slaney _ Wexford Harbour.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Liffey and Dublin Bay.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Moy _ Killala Bay.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Corrib.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Ovoca-Vartry.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Shannon Estuary South.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Laune-Maine-Dingle Bay.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Lower Shannon (C).csv', '/content/drive/MyDrive/water paper/new added columns last/f_Lower Shannon (A).csv', '/content/drive/MyDrive/water paper/new added columns last/f_Sligo Bay _ Drowse.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Lower Shannon (D).csv', '/content/drive/MyDrive/water paper/new added columns last/f_Tralee Bay-Feale.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Shannon Estuary North.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Erriff-Clew Bay.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Gweebarra-Sheephaven.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Upper Shannon (F).csv', '/content/drive/MyDrive/water paper/new added columns last/f_Upper Shannon (C).csv', '/content/drive/MyDrive/water paper/new added columns last/f_Lower Shannon (B).csv', '/content/drive/MyDrive/water paper/new added columns last/f_Lough Swilly.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Galway Bay South East.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Foyle.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Dunmanus-Bantry-Kenmare.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Upper Shannon (A).csv', '/content/drive/MyDrive/water paper/new added columns last/f_Nanny-Delvin.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Upper Shannon (D).csv', '/content/drive/MyDrive/water paper/new added columns last/f_Colligan-Mahon.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Owenavorragh.csv', '/content/drive/MyDrive/water paper/new added columns last/f_foyal.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Galway Bay North.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Mal Bay.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Lough Neagh _ Lower Bann.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Donegal Bay North.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Upper Shannon (B).csv', '/content/drive/MyDrive/water paper/new added columns last/f_Donagh-Moville.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Upper Shannon (E).csv', '/content/drive/MyDrive/water paper/new added columns last/f_Blackwater_Munster.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Newry, Fane, Glyde and Dee.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Lee, Cork Harbour and Youghal Bay.csv', '/content/drive/MyDrive/water paper/new added columns last/f_Cork Harbour, Moy Killala.csv']
[                              WaterbodyName Waterbodytype SampleDate  \
0             Ballyteigue-Bannow, Adamstown         River   07-07-10
1             Ballyteigue-Bannow, Adamstown         River   14-09-10
2             Ballyteigue-Bannow, Adamstown         River   17-11-10
3             Ballyteigue-Bannow, Adamstown         River   09-03-11
4             Ballyteigue-Bannow, Adamstown         River   29-06-11
...                                     ...           ...        ...
2186  Ballyteigue-Bannow, Waterford Harbour       Coastal   13-09-21
2187  Ballyteigue-Bannow, Waterford Harbour       Coastal   31-05-22
2188  Ballyteigue-Bannow, Waterford Harbour       Coastal   10-08-22
2189  Ballyteigue-Bannow, Waterford Harbour       Coastal   01-06-23
2190  Ballyteigue-Bannow, Waterford Harbour       Coastal   20-07-23

      Alkalinity-total (as CaCO3)  Ammonia-Total (as N)  BOD - 5 days (Total)  \
0                            30.0                   NaN                   NaN
1                             NaN                   NaN                   NaN
2                            35.0                   NaN                   NaN
3                            36.0                   NaN                   NaN
4                            32.0                   NaN                   NaN
...                           ...                   ...                   ...
2186                          NaN              0.058333                   NaN
2187                          NaN              0.027286              1.344444
2188                          NaN              0.019917              1.300000
2189                          NaN              0.017000              1.150000
2190                          NaN              0.078143                   NaN

      Chloride  Conductivity @25Â°C  Dissolved Oxygen  \
0         29.0                207.0         66.000000
1         40.0                212.0         67.000000
2         28.0                212.0         65.000000
3         28.0                194.0         67.000000
4         28.0                216.0         38.000000
...        ...                  ...               ...
2186       NaN                  NaN         95.250000
2187       NaN                  NaN        115.285714
2188       NaN                  NaN        117.750000
2189       NaN                  NaN        112.500000
2190       NaN                  NaN         98.714286

      ortho-Phosphate (as P) - unspecified        pH  Temperature  \
0                                      NaN  6.000000    11.500000
1                                      NaN  6.500000    11.100000
2                                      NaN  6.300000    11.000000
3                                      NaN  6.200000    10.900000
4                                      NaN  6.200000    11.100000
...                                    ...       ...          ...
2186                              0.010417  8.041667    16.150000
2187                              0.006720  8.121429    13.114286
2188                              0.006800  8.100000    16.441667
2189                                   NaN  8.200000    15.150000
2190                              0.033714  7.985714    15.421429

      Total Hardness (as CaCO3)  Total Oxidised Nitrogen (as N)  \
0                          53.0                        3.110000
1                          50.0                        3.390000
2                          74.0                        3.930000
3                          41.0                        3.200000
4                          57.0                        2.700000
...                         ...                             ...
2186                        NaN                        0.035333
2187                        NaN                        0.026625
2188                        NaN                        0.064500
2189                        NaN                        0.062250
2190                        NaN                        0.118429

      Total Hardness (as CaCO3).1  Nitrate (as N)
0                            53.0             NaN
1                            50.0             NaN
2                            74.0             NaN
3                            41.0             NaN
4                            57.0             NaN
...                           ...             ...
2186                          NaN             NaN
2187                          NaN             NaN
2188                          NaN             NaN
2189                          NaN             NaN
2190                          NaN             NaN

[2191 rows x 16 columns],                          WaterbodyName Waterbodytype SampleDate  \
0                Bandonllen, Abisdealy          Lake   21-08-07
1                Bandonllen, Abisdealy          Lake   17-10-07
2                Bandonllen, Abisdealy          Lake   30-04-08
3                Bandonllen, Abisdealy          Lake   30-07-08
4                Bandonllen, Abisdealy          Lake   11-09-08
...                                ...           ...        ...
2900  Bandonllen, Upper Bandon Estuary  Transitional   17-05-23
2901  Bandonllen, Upper Bandon Estuary  Transitional   22-06-23
2902  Bandonllen, Upper Bandon Estuary  Transitional   19-07-23
2903  Bandonllen, Upper Bandon Estuary  Transitional   24-07-23
2904  Bandonllen, Upper Bandon Estuary  Transitional   21-08-23

      Alkalinity-total (as CaCO3)  Ammonia-Total (as N)  BOD - 5 days (Total)  \
0                            46.0                   NaN                   NaN
1                            52.0                   NaN                   NaN
2                            50.0                   NaN                   NaN
3                            84.0                   NaN                   NaN
4                            44.0                   NaN                   NaN
...                           ...                   ...                   ...
2900                          NaN                   NaN                   NaN
2901                          NaN              0.088750                  1.85
2902                          NaN              0.020000                  2.00
2903                          NaN              0.038000                  2.05
2904                          NaN              0.057333                  1.20

      Chloride  Conductivity @25Â°C  Dissolved Oxygen  \
0          NaN                  NaN         54.300000
1          NaN                  NaN         48.950000
2          NaN                  NaN         58.950000
3          NaN                  NaN         34.500000
4          NaN                  NaN         52.250000
...        ...                  ...               ...
2900       NaN                  NaN         98.200000
2901       NaN                  NaN        102.000000
2902       NaN                  NaN        100.400000
2903       NaN                  NaN         89.750000
2904       NaN                  NaN         88.666667

      ortho-Phosphate (as P) - unspecified     pH  Temperature  \
0                                 0.006000  7.900    17.300000
1                                 0.006000  7.600    15.600000
2                                 0.006000  7.700    13.700000
3                                 0.006000  7.400    18.900000
4                                 0.006000  7.500    14.700000
...                                    ...    ...          ...
2900                                   NaN  7.800    13.500000
2901                              0.013950  8.025    21.125000
2902                              6.920000  7.500    16.800000
2903                              0.045000  7.575    17.075000
2904                              0.045667  7.400    16.833333

      Total Hardness (as CaCO3)  Total Oxidised Nitrogen (as N)  \
0                          76.0                             NaN
1                          66.0                             NaN
2                          66.0                             NaN
3                          74.0                             NaN
4                          66.0                             NaN
...                         ...                             ...
2900                        NaN                             NaN
2901                        NaN                        1.017500
2902                        NaN                             NaN
2903                        NaN                        1.165000
2904                        NaN                        1.966667

      Total Hardness (as CaCO3).1  Nitrate (as N)
0                            76.0             NaN
1                            66.0             NaN
2                            66.0             NaN
3                            74.0             NaN
4                            66.0             NaN
...                           ...             ...
2900                          NaN             NaN
2901                          NaN             NaN
2902                          NaN             NaN
2903                          NaN             NaN
2904                          NaN             NaN

[2905 rows x 16 columns],                       WaterbodyName Waterbodytype SampleDate  \
0                 Barrow, Adamstown         River   07-07-10
1                 Barrow, Adamstown         River   14-09-10
2                 Barrow, Adamstown         River   17-11-10
3                 Barrow, Adamstown         River   09-03-11
4                 Barrow, Adamstown         River   29-06-11
...                             ...           ...        ...
12375  Barrow, Upper Barrow Estuary         River   06-09-22
12376  Barrow, Upper Barrow Estuary         River   29-11-22
12377  Barrow, Upper Barrow Estuary         River   13-02-23
12378  Barrow, Upper Barrow Estuary         River   30-05-23
12379  Barrow, Upper Barrow Estuary         River   18-07-23

       Alkalinity-total (as CaCO3)  Ammonia-Total (as N)  \
0                             30.0                   NaN
1                              NaN                   NaN
2                             35.0                   NaN
3                             36.0                   NaN
4                             32.0                   NaN
...                            ...                   ...
12375                          NaN              0.034333
12376                          NaN              0.020500
12377                          NaN              0.018750
12378                          NaN              0.027000
12379                          NaN              0.042000

       BOD - 5 days (Total)  Chloride  Conductivity @25Â°C  Dissolved Oxygen  \
0                       NaN      29.0                207.0             66.00
1                       NaN      40.0                212.0             67.00
2                       NaN      28.0                212.0             65.00
3                       NaN      28.0                194.0             67.00
4                       NaN      28.0                216.0             38.00
...                     ...       ...                  ...               ...
12375              1.233333       NaN                  NaN             94.50
12376                   NaN       NaN                  NaN             95.50
12377                   NaN       NaN                  NaN             99.25
12378                   NaN       NaN                  NaN            114.75
12379              1.450000       NaN                  NaN             87.75

       ortho-Phosphate (as P) - unspecified    pH  Temperature  \
0                                       NaN  6.00        11.50
1                                       NaN  6.50        11.10
2                                       NaN  6.30        11.00
3                                       NaN  6.20        10.90
4                                       NaN  6.20        11.10
...                                     ...   ...          ...
12375                               0.01174  8.20        17.75
12376                               0.03900  8.10         8.80
12377                               0.00775  8.30         8.00
12378                               0.00520  8.45        18.30
12379                               0.06000  7.85        16.10

       Total Hardness (as CaCO3)  Total Oxidised Nitrogen (as N)  \
0                           53.0                           3.110
1                           50.0                           3.390
2                           74.0                           3.930
3                           41.0                           3.200
4                           57.0                           2.700
...                          ...                             ...
12375                        NaN                           1.550
12376                        NaN                           4.725
12377                        NaN                           6.150
12378                        NaN                           3.950
12379                        NaN                           2.150

       Total Hardness (as CaCO3).1  Nitrate (as N)
0                             53.0             NaN
1                             50.0             NaN
2                             74.0             NaN
3                             41.0             NaN
4                             57.0             NaN
...                            ...             ...
12375                          NaN             NaN
12376                          NaN             NaN
12377                          NaN             NaN
12378                          NaN             NaN
12379                          NaN             NaN

[12380 rows x 16 columns],                                  WaterbodyName Waterbodytype SampleDate  \
0     Blacksod-Broadhaven, Blacksod-Broadhaven          Lake   23-04-07
1     Blacksod-Broadhaven, Blacksod-Broadhaven          Lake   23-07-07
2     Blacksod-Broadhaven, Blacksod-Broadhaven          Lake   20-08-07
3     Blacksod-Broadhaven, Blacksod-Broadhaven          Lake   18-09-07
4     Blacksod-Broadhaven, Blacksod-Broadhaven          Lake   17-04-08
...                                        ...           ...        ...
1799  Blacksod-Broadhaven, Blacksod-Broadhaven  Transitional   20-07-21
1800  Blacksod-Broadhaven, Blacksod-Broadhaven  Transitional   31-08-21
1801  Blacksod-Broadhaven, Blacksod-Broadhaven  Transitional   24-05-23
1802  Blacksod-Broadhaven, Blacksod-Broadhaven  Transitional   12-07-23
1803  Blacksod-Broadhaven, Blacksod-Broadhaven  Transitional   23-08-23

      Alkalinity-total (as CaCO3)  Ammonia-Total (as N)  BOD - 5 days (Total)  \
0                             NaN                   NaN                   NaN

In [ ]:

# Save the DataFrame as a CSV file to the content folder in Colab
merged_df.to_csv('/content/your_output_file.csv', index=False)

In [ ]:
merged_df.info()

In [ ]:

# # count the number of missing values in each row
# num_missing = merged_df.isnull().sum(axis=1)

# # filter the rows with more than 3 missing values
# filtered_data = merged_df[num_missing <= 8]

# # save the filtered data to a new CSV file
# #filtered_data.to_csv('testX.csv', index=False)

# filtered_data.info()
# filtered_data.isnull().sum()

In [ ]:
max_blank_values = 11
df_cleaned = merged_df.dropna(thresh=df.shape[1] - max_blank_values + 1)
# Save the DataFrame as a CSV file to the content folder in Colab
df_cleaned.to_csv('/content/final_dropped.csv', index=False)

In [ ]:
df_cleaned.describe()

In [ ]:
df_cleaned.isnull().sum()

In [ ]:
new_df.to_csv('/content/final_null.csv', index=False)